rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - sudo apt-get update
  - sudo apt-get install redis-server
bundler_args: --without development
script:
  - bundle exec cucumber
  - bundle exec rake
branches:
  only:
      - master

